language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: c09iOoYdpBcRHXrDcAOsdVY5O3Qu4yPUBK3SL33s0o/j5wCBnFApQ0z92mIjpfgQVh21HdjJ3LG4qwM51xRBkr0I0Zn6gjD//8FKdXFT0g0+HZqjNxB04r6Poki+WSVuwzVOPQJ9ioNwsx9MdMecSjLY0rVFtnHrw9E3LSdkwY2Xg49I+c0XVxduZPIWXN/v1++kundZcoB3MQ08pP28O4yvZjAcEhI5C9t/LugXYOKoFTu7xRf3RL36XkUxaBY3Dpv0+W5Qb119d6Mp5ePJVACjbQlJwgAJRSVX4XMr4uX0b/3+vSPW52S5si40PJ9kBrIhoPfCT1k2xd/XlEOIB3JOXKAiGyXD3OK/vE1nPb+tGIcnAFEW3ZaHnYuR81OUDHqmwypdpyk6jPGBGdkaMVU3vZBZgsq1ULdmcVO3oUFVY6zuupJklmXUgMyjihYcWmTFYN1zZ+AtUWUcDa8KS1T296dxO4TipHwl5KxWxO8yE0rXuWWjGXI+NoYawtYaezAte7D7M9spbFM2GxRKpmnnpQcIjrHUFYwK9kqtM9cS0iKS4zHZrVrBrzrMpFA61blifM/Wusaocjv91zFEqvn/RDHQsGwxbdUPtbdMhw24GJ/jt28KhToFcRT16Ou4irGonIKTLFcUNGFEJxVTYnQ6fm0QX7ciJTNwE+59ALg=
