language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: dddbcurWgMjvPfFmW8BD38z6z689lXblGDPien+BMmukIG5tzpAI7TOEHipBLXgJYBIXaOSv7QY7T/FgP83S0eHgxOMTAoMA5Pty6Y721F5/TlfXlIYlanlka0tA1GB4Jijs5zoEClS+PQb2C2BfFuwbXQ9EZMLyn1e9h2yHyxFq9rPiLlamKETlamlQMezs66+Fhdx9/xEJHIW44DSVXP7zIbHz2uotQ+C9hgJWmOF7/lVHgFtsFunH85On7i0TVOB8ZFzsZCC5svJr2m4ZnuqsRXACixTlvtDsHibPJUwYYJM4QyvbXf8Mcos5tKAmETlTaP35Pyv9jkq8pWl+ki9z8Q6qd/sgGoUmjt+X/eA2nEJktVAiTvF+W6+XLAmHJPa04EYhFMf7eiCRzjKPWP9IxAsAj18ycGL/RPhwFcCgQh8OrwOS+7cx+ITf8Ul6lwjQNVvaPAyUrJzvGJS6uZGBmaU6xbR66bphxP45OpdsJikEKVLGHfOYPqFcBOQqhBF6CgvIdGdvEPDlIV894+BlVYUtErMfRoopGhJMxAk4txe5Xt8NRija8iJbXTn8FUbMOaqNrGM0/PKfdOT+t7b8dl+wLdVov3YkX+fn+tevDyfaqKVLWYJcg1a69hZCIUowrED9moHwCblK2ZfJYtbmEitktkDFDq07rAkY0mo=
